var data = {
  about:
    "<div class=''> <h1 class='h1'>Personal Information</h1> <hr>  <div class='section'> <img class='avatar' src='img/1.png'/> <div class='sectionContact'> <p><strong>Phone:</strong> (718)-413-0876</p> <p> <strong>Email:</strong> karyshkov@gmail.com</p> </div></div> <h1 class='h1'>Professional Profile</h1> <hr> <div class='section'> <p class='copy'>Bright and talented in user-experience design with the proven ability to combine creative and usability viewpoints resulting in world-class Web and mobile applications. A quick learner who can absorb new ideas and can communicate clearly and effectively. Team player with good listening skills and innovative ideas to make attractive design. Worked simultaneously on multiple tasks while dealing with changing priorities; always maintained a strong sense of accountability and ability to meet deadlines.</p></div></div>",

  experience:
    "<div class=''> <h1 class='h1'>Work Experience</h1> <hr> <div class='section'> <div class='title-experience'> <h2>Digital Graphic Designer</h2> <h3 class='h3'>New York University</h3> </div> <div class='sectionInside'> <p class='years'>JULY 2017 - PRESENT</p> </div></div> <div class='section'> <p class='copy'> <ol class='boolet'><li>Design of brochures, leaflets, and posters, the designing of e-mails, animated banners for both internal and external markets.</li> <li>Prepare work to be completed by gathering information and materials needed for the project. </li><li> Plan concept by studying information and materials. Illustrate concept by designing rough layout of art and copy regarding arrangement, size, type size and style, and related aesthetic concepts.</li><li> Help the team complete projects by coordinating with outside agencies, art services, printers, etc.</li><li> Contribute to team effort by accomplishing related results as needed.</li></ol></p> </div> <hr> <div class='section'> <div class='title-experience'> <h2>UI/UX Interaction Designer</h2> <h3 class='h3'>CURB, Verifone Inc., New York.</h3> </div> <div class='sectionInside'> <p class='years'>MAY 2016 - JULY 2017</p> </div></div> <div class='section'> <p class='copy'> <ol class='boolet'><li>Responsible for the look feel of a site and mobile app.</li> <li>Create a clean and functional design based on the requirements already identified.</li><li> Conceiving, wireframing, sketching, prototyping, and mocking up user experiences for digital products.</li><li>Interactivity and Animation.</li><li>Website banners advertisment, Brochures, Flyers.</li> <li>Designed instead of created advertisement for new taxi driver monitors and payment terminals.</li> </ol></p> </div> <hr> <div class='section'> <div class='title-experience'> <h2>Multimedia Designer</h2> <h3 class='h3'>PR Newswire, a MultiVu Creative. New York.</h3> </div> <div class='sectionInside'> <p class='years'>APRIL 2015 - MAY 2016</p> </div></div> <div class='section'> <p class='copy'> <ol class='boolet'><li>Responsible for the look feel of a site and mobile app.</li> <li>Create a clean and functional design based on the requirements already identified.</li><li> Conceiving, wireframing, sketching, prototyping, and mocking up user experiences for digital products.</li><li>Interactivity and Animation.</li><li>Website banners advertisment, Brochures, Flyers.</li> <li>Designed instead of created advertisement for new taxi driver monitors and payment terminals.</li> </ol></p> </div> </div>",

  skills:
    "<div class=''> <h1 class='h1'>Technical Skills</h1> <hr class='skills'>  <div class='skills'> <img class='skills-icons' src='img/p.png'/> <img class='skills-icons' src='img/i.png'/> <img class='skills-icons' src='img/h.png'/> <img class='skills-icons' src='img/c.png'/> </div> <div class='skills'> <img class='skills-icons' src='img/p.png'/> <img class='skills-icons' src='img/i.png'/> <img class='skills-icons' src='img/h.png'/> <img class='skills-icons' src='img/c.png'/> </div> <div class='skills'> <img class='skills-icons' src='img/h.png'/> <img class='skills-icons' src='img/i.png'/> <img class='skills-icons' src='img/c.png'/> <img class='skills-icons' src='img/h.png'/> </div> <div class='skills'> <img class='skills-icons' src='img/p.png'/> <img class='skills-icons' src='img/h.png'/> <img class='skills-icons' src='img/i.png'/> <img class='skills-icons' src='img/c.png'/> </div> </div>",
};
